name: Deploy a build

on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  prep:
    uses: ./.github/workflows/shared_var
    with:
      tag: ${{ github.event.inputs.tag }}
  test:
    runs-on: ubuntu-18.04
    needs: prep
    steps:
      - run: |
          echo ${{ needs.prep.outputs.ref }}
          echo ${{ needs.prep.outputs.environment }}
          echo ${{ needs.prep.outputs.release_version }}
